print(":".join(["spam","eggs","ham"]))
print("hello ME".replace("ME","world"))
print("check start".startswith("check"))
print("check end".endswith("end"))
print("making it UPPER case".upper())
print("MAKING IT lower CASE".lower())
print("spam:eggs:ham".split(":"))
print("------math------------")
print(min(1,2,3,4,5,5,6,7,8))
print(max(1,2,3,4,5,5,6,7,8))
print(abs(-23))
print(abs(23))
print(sum([1,2,3,4,5,5,6,7,8]))